v0:
  environment_cfg/robot_model: BERKELY_HUMANOID
  environment_cfg/box_height: 0.5
  environment_cfg/oracle/params/nominal_height: 0.515

v1:
  environment_cfg/robot_model: G1_DC
  environment_cfg/box_height: 1.0
  environment_cfg/oracle/params/nominal_height: 0.74

v2:
  environment_cfg/robot_model: H1_DC
  environment_cfg/box_height: 1.5
  environment_cfg/oracle/params/nominal_height: 1.05