# product mode
# environment_cfg/robot_model:
# - HECTOR_V1P5
# - BERKELEY_HUMANOID

# environment_cfg/oracle/params/nominal_height:
# - 0.515
# - 0.5 

#  list mode (set as default)
v0:
  environment_cfg/robot_model: HECTOR_V1P5
v1:
  environment_cfg/robot_model: BERKELEY_HUMANOID
  environment_cfg/oracle/params/nominal_height: 0.515
